#!/usr/bin/env python3
# Copyright (c) 2025, DYROS.
#
# Read absolute world-frame foot targets (config/footcommands_global.csv) and
# write one cube ("stepping stone") per footstep into a MuJoCo scene XML, so the
# planned footholds can be visualized / stepped on in simulation.
#
# The cubes are written into a marked region of the XML and the script is
# idempotent: re-running replaces the previously generated region rather than
# appending. Existing hand-authored geoms are left untouched.
#
# Frame note:
#   footcommands_global.csv is in the real world frame (its initial stance foot is
#   anchored at the spawn foot pose, matching deploy.yaml global_init_*foot), so the
#   targets already line up with the MuJoCo scene. A ground plane is placed at the
#   lowest pos_z; each stepping cube spans from that plane up to its pos_z (variable
#   height). Use --offset-* to nudge, or --center to re-center the lateral span on y=0.
#
# Usage:
#   python3 cmd/gen_footstep_scene.py
#   python3 cmd/gen_footstep_scene.py --size 0.12 0.07 --offset-y 0.0
#   python3 cmd/gen_footstep_scene.py --csv config/footcommands_global.csv \
#       --xml /home/yong/unitree_ws/unitree_mujoco/unitree_robots/g1/scene_29dof_footstep.xml

import argparse
import csv
import math
import os

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJ_DIR = os.path.dirname(_THIS_DIR)
DEFAULT_CSV = os.path.join(_PROJ_DIR, "config", "footcommands_global.csv")
DEFAULT_XML = "/home/yong/g1_ws/unitree_mujoco/unitree_robots/g1/scene_29dof_footstep.xml"

BEGIN_MARK = "<!-- BEGIN footstep cubes (auto-generated by gen_footstep_scene.py) -->"
END_MARK = "<!-- END footstep cubes -->"

# rgba per swing foot (alpha < 1 so overlaps are visible)
# COLOR_R = "0.80 0.30 0.30 1"  # right foot
# COLOR_L = "0.30 0.45 0.80 1"  # left foot

COLOR_R = "0.45 0.45 0.5 1"  # right foot
COLOR_L = "0.45 0.45 0.5 1"  # left foot
COLOR_GROUND = "0.7 0.6 0.5 1"

def read_targets(path):
    with open(path, newline="") as f:
        reader = csv.reader(f)
        header = [h.strip().lower() for h in next(reader)]
        idx = {name: i for i, name in enumerate(header)}
        for c in ["foot", "pos_x", "pos_y", "pos_z", "yaw"]:
            if c not in idx:
                raise ValueError(f"missing required column '{c}' in {path}")
        rows = []
        for cells in reader:
            cells = [c.strip() for c in cells]
            if not cells or all(c == "" for c in cells):
                continue
            foot = cells[idx["foot"]].strip().lower()
            rows.append({
                "foot": "R" if foot in ("r", "right") else "L",
                "x": float(cells[idx["pos_x"]]),
                "y": float(cells[idx["pos_y"]]),
                "z": float(cells[idx["pos_z"]]),
                "yaw": float(cells[idx["yaw"]]),
            })
    if not rows:
        raise ValueError(f"no data rows in {path}")
    return rows


def yaw_to_quat(yaw):
    return (math.cos(yaw / 2.0), 0.0, 0.0, math.sin(yaw / 2.0))


def build_cubes(rows, size_xy, off, center_y, plane_margin):
    """Build a ground plane at min(pos_z) and variable-height cubes up to each target."""
    sx, sy = size_xy
    ox, oy, oz = off
    if center_y:
        ys = [r["y"] for r in rows]
        oy += -0.5 * (min(ys) + max(ys))  # straddle y=0

    xs = [r["x"] + ox for r in rows]
    ys = [r["y"] + oy for r in rows]
    zs_top = [r["z"] + oz for r in rows]
    z_base = min(zs_top)

    plane_cx = 0.5 * (min(xs) + max(xs))
    plane_cy = 0.5 * (min(ys) + max(ys))
    plane_hx = 0.5 * (max(xs) - min(xs)) + plane_margin
    plane_hy = 0.5 * (max(ys) - min(ys)) + plane_margin

    lines = [
        f'    <geom name="footstep_ground" type="plane" '
        f'pos="{plane_cx:.4f} {plane_cy:.4f} {z_base:.4f}" '
        f'size="{plane_hx:.4f} {plane_hy:.4f} 0.1" '
        f'rgba="{COLOR_GROUND}" material="MatPlane2" group="2"/>',
    ]

    for i, r in enumerate(rows):
        x = r["x"] + ox
        y = r["y"] + oy
        z_top = r["z"] + oz
        height = z_top - z_base
        if height < 1e-4:
            continue  # foothold sits on the base plane; no pillar needed
        hz = height * 0.5
        zc = z_base + hz
        qw, qx, qy, qz = yaw_to_quat(r["yaw"])
        color = COLOR_R if r["foot"] == "R" else COLOR_L
        lines.append(
            f'    <geom name="footstep_cube_{i:02d}" type="box" '
            f'size="{sx:.4f} {sy:.4f} {hz:.4f}" '
            f'pos="{x:.4f} {y:.4f} {zc:.4f}" '
            f'quat="{qw:.6f} {qx:.6f} {qy:.6f} {qz:.6f}" '
            f'rgba="{color}"/>'
        )
    return f"    {BEGIN_MARK}\n" + "\n".join(lines) + f"\n    {END_MARK}"


def inject(xml_text, block):
    b = xml_text.find(BEGIN_MARK)
    e = xml_text.find(END_MARK)
    if b != -1 and e != -1:
        # replace the existing region (incl. leading indentation of the begin marker)
        line_start = xml_text.rfind("\n", 0, b) + 1
        end_after = e + len(END_MARK)
        return xml_text[:line_start] + block + xml_text[end_after:]
    # otherwise insert just before </worldbody>
    close = xml_text.rfind("</worldbody>")
    if close == -1:
        raise ValueError("no </worldbody> found in scene XML")
    line_start = xml_text.rfind("\n", 0, close) + 1
    return xml_text[:line_start] + block + "\n" + xml_text[line_start:]


if __name__ == "__main__":
    p = argparse.ArgumentParser(description="Generate footstep cubes in a MuJoCo scene XML.")
    p.add_argument("--csv", default=DEFAULT_CSV, help="footcommands_global.csv path")
    p.add_argument("--xml", default=DEFAULT_XML, help="MuJoCo scene XML to edit")
    p.add_argument("--size", nargs=2, type=float, default=[0.1, 0.06],
                   metavar=("HX", "HY"), help="cube horizontal half-extents [m]")
    p.add_argument("--plane-margin", type=float, default=3.0,
                   help="extra half-length added around the footstep bounding box for the ground plane [m]")
    p.add_argument("--offset-x", type=float, default=-0.0)
    p.add_argument("--offset-y", type=float, default=0.0)
    p.add_argument("--offset-z", type=float, default=0.0)
    p.add_argument("--center", action="store_true",
                   help="re-center the lateral (y) span on y=0 (off by default; the "
                        "CSV is already in the real world frame)")
    args = p.parse_args()

    rows = read_targets(args.csv)
    block = build_cubes(rows, args.size,
                        (args.offset_x, args.offset_y, args.offset_z),
                        center_y=args.center,
                        plane_margin=args.plane_margin)

    with open(args.xml) as f:
        xml_text = f.read()
    with open(args.xml, "w") as f:
        f.write(inject(xml_text, block))

    print(f"Wrote ground plane + {len(rows)} footstep targets into {args.xml} "
          f"(z_base={min(r['z'] for r in rows) + args.offset_z:.4f})")
