#!/usr/bin/env python3
# Copyright (c) 2025, DYROS.
#
# Like cmd/gen_footstep_scene.py, but each footstep target additionally gets
# FOUR ArUco markers (3x3-bit, "3 cm" class) on its top surface so an onboard
# camera (D435i) can estimate the target pose precisely (16 corner points per
# target -> robust PnP).
#
# Outputs:
#   1. Scene XML edits (same marked region as gen_footstep_scene.py for the
#      geoms + an extra marked region in <asset> for marker textures), so
#      re-running either script replaces the previous generated block.
#   2. Marker texture PNGs      -> <xml_dir>/aruco_markers/marker_###.png
#   3. Board metadata JSON      -> config/aruco_board.json (read by
#      cmd/aruco_footstep_perception.py to build PnP object points)
#   4. Printable per-target sheets (real world) -> <xml_dir>/aruco_markers/
#      sheet_target_##.png at --dpi (markers at true physical scale).
#
# Marker ids: target i owns ids [4i, 4i+1, 4i+2, 4i+3]
#   (front-left, front-right, back-right, back-left in the target frame;
#    x = footstep yaw direction, origin = footstep center on the top surface).
#
# Usage:
#   python3 cmd/gen_aruco_footstep_scene.py
#   python3 cmd/gen_aruco_footstep_scene.py --marker-size 0.03 --marker-spread 0.05
#   python3 cmd/gen_aruco_footstep_scene.py --shape box --size 0.1 0.08

import argparse
import math
import os
import sys

import numpy as np
import cv2

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import aruco_common as ac
from gen_footstep_scene import (
    read_targets, yaw_to_quat, build_footsteps, strip_start_platform, inject,
    BEGIN_MARK, END_MARK, DEFAULT_CSV, DEFAULT_XML,
    DEFAULT_PLATFORM_SIZE, DEFAULT_PLATFORM_TOP,
)

ASSET_BEGIN = "<!-- BEGIN aruco marker assets (auto-generated by gen_aruco_footstep_scene.py) -->"
ASSET_END = "<!-- END aruco marker assets -->"

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJ_DIR = os.path.dirname(_THIS_DIR)
DEFAULT_BOARD = os.path.join(_PROJ_DIR, "config", "aruco_board.json")

MARKER_HALF_THICK = 0.0005   # [m] visual-only thin box half thickness
MARKER_LIFT = 0.0006         # [m] center height above the footstep top face


def inject_region(xml_text, block, begin, end, closing_tag):
    """Replace the begin..end region, or insert before closing_tag."""
    b = xml_text.find(begin)
    e = xml_text.find(end)
    if b != -1 and e != -1:
        line_start = xml_text.rfind("\n", 0, b) + 1
        return xml_text[:line_start] + block + xml_text[e + len(end):]
    close = xml_text.rfind(closing_tag)
    if close == -1:
        raise ValueError(f"no {closing_tag} found in scene XML")
    line_start = xml_text.rfind("\n", 0, close) + 1
    return xml_text[:line_start] + block + "\n" + xml_text[line_start:]


def write_marker_textures(dictionary, n_targets, tex_dir, quiet_modules, bits):
    os.makedirs(tex_dir, exist_ok=True)
    scale = None
    for mid in range(ac.MARKERS_PER_TARGET * n_targets):
        img, scale = ac.marker_image(dictionary, mid, modules_px=32,
                                     quiet_modules=quiet_modules, bits=bits)
        cv2.imwrite(os.path.join(tex_dir, f"marker_{mid:03d}.png"), img)
    return scale


def build_marker_assets(n_markers, tex_rel_dir):
    lines = [f"    {ASSET_BEGIN}"]
    for mid in range(n_markers):
        lines.append(
            f'    <texture name="aruco_m{mid:03d}" type="2d" '
            f'file="{tex_rel_dir}/marker_{mid:03d}.png"/>')
        lines.append(
            f'    <material name="aruco_m{mid:03d}" texture="aruco_m{mid:03d}" '
            f'specular="0" shininess="0" reflectance="0" emission="0.35"/>')
    lines.append(f"    {ASSET_END}")
    return "\n".join(lines)


def build_marker_geoms(rows, off, marker_size, marker_spread, tex_scale):
    """Visual-only textured thin boxes on each footstep top face."""
    ox, oy, oz = off
    half = marker_size * tex_scale / 2.0  # geom includes the white quiet zone
    centers = ac.marker_centers(marker_spread)
    lines = []
    for i, r in enumerate(rows):
        x0, y0, z_top = r["x"] + ox, r["y"] + oy, r["z"] + oz
        yaw = r["yaw"]
        c, s = math.cos(yaw), math.sin(yaw)
        qw, qx, qy, qz = yaw_to_quat(yaw)
        for j, (mx, my) in enumerate(centers):
            mid = ac.MARKERS_PER_TARGET * i + j
            gx = x0 + c * mx - s * my
            gy = y0 + s * mx + c * my
            gz = z_top + MARKER_LIFT
            lines.append(
                f'    <geom name="aruco_m{mid:03d}" type="box" '
                f'size="{half:.4f} {half:.4f} {MARKER_HALF_THICK:.4f}" '
                f'pos="{gx:.4f} {gy:.4f} {gz:.4f}" '
                f'quat="{qw:.6f} {qx:.6f} {qy:.6f} {qz:.6f}" '
                f'material="aruco_m{mid:03d}" '
                f'contype="0" conaffinity="0" group="1"/>')
    return "\n".join(lines)


def write_print_sheets(dictionary, rows, out_dir, marker_size, marker_spread,
                       quiet_modules, bits, dpi):
    """Per-target printable sheet: 4 markers at true physical scale."""
    px_per_m = dpi / 0.0254
    scale = (bits + 2 + 2 * quiet_modules) / float(bits + 2)
    tile = marker_size * scale                    # marker incl. quiet zone [m]
    side = 2 * marker_spread + tile + 0.02        # canvas side [m] (+1cm margin)
    W = int(round(side * px_per_m))
    canvas_tpl = np.full((W, W), 255, np.uint8)

    def to_px(x, y):  # target frame (x fwd = sheet up, y left = sheet left)
        u = int(round(W / 2.0 - y * px_per_m))
        v = int(round(W / 2.0 - x * px_per_m))
        return u, v

    for i, r in enumerate(rows):
        canvas = canvas_tpl.copy()
        for j, (mx, my) in enumerate(ac.marker_centers(marker_spread)):
            mid = ac.MARKERS_PER_TARGET * i + j
            img, _ = ac.marker_image(dictionary, mid, modules_px=32,
                                     quiet_modules=quiet_modules, bits=bits,
                                     flip_v=False)
            t = int(round(tile * px_per_m))
            img = cv2.resize(img, (t, t), interpolation=cv2.INTER_NEAREST)
            u, v = to_px(mx, my)
            canvas[v - t // 2:v - t // 2 + t, u - t // 2:u - t // 2 + t] = img
        # center cross + forward arrow (sheet "up" = target +x = walking dir)
        u0, v0 = to_px(0, 0)
        cv2.drawMarker(canvas, (u0, v0), 0, cv2.MARKER_CROSS, 20, 1)
        cv2.arrowedLine(canvas, (u0, v0 - 30), (u0, v0 - 70), 0, 2, tipLength=0.3)
        cv2.putText(canvas, f"target {i:02d} ({r['foot']})  x->up",
                    (10, W - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, 0, 1)
        cv2.imwrite(os.path.join(out_dir, f"sheet_target_{i:02d}.png"), canvas)


if __name__ == "__main__":
    p = argparse.ArgumentParser(
        description="Generate footstep geoms + 4 ArUco markers per target in a MuJoCo scene XML.")
    p.add_argument("--csv", default=DEFAULT_CSV)
    p.add_argument("--xml", default=DEFAULT_XML)
    p.add_argument("--board", default=DEFAULT_BOARD,
                   help="output board metadata JSON (read by the perception node)")
    p.add_argument("--shape", choices=["box", "cylinder"], default="box")
    p.add_argument("--size", nargs=2, type=float, default=[0.1, 10.06],
                   metavar=("HX", "HY"))
    p.add_argument("--plane-margin", type=float, default=3.0)
    p.add_argument("--platform-size", nargs=2, type=float,
                   default=list(DEFAULT_PLATFORM_SIZE), metavar=("HX", "HY"))
    p.add_argument("--platform-top", type=float, default=DEFAULT_PLATFORM_TOP)
    p.add_argument("--offset-x", type=float, default=-0.03)
    p.add_argument("--offset-y", type=float, default=0.0)
    p.add_argument("--offset-z", type=float, default=0.0)
    p.add_argument("--center", action="store_true")
    # marker parameters
    p.add_argument("--marker-size", type=float, default=ac.DEFAULT_MARKER_SIZE,
                   help="black-border side length [m] (default 0.03 = 3x3 cm)")
    p.add_argument("--marker-spread", type=float, default=ac.DEFAULT_MARKER_SPREAD,
                   help="|x|=|y| offset of the 4 marker centers [m]")
    p.add_argument("--dict-bits", type=int, default=ac.DEFAULT_DICT_BITS,
                   help="marker bit-grid size (default 4 -> standard DICT_4X4; "
                        "3 -> custom 3x3-bit dict, only reliable with few ids)")
    p.add_argument("--dict-seed", type=int, default=ac.DEFAULT_DICT_SEED)
    p.add_argument("--quiet-modules", type=int, default=ac.DEFAULT_QUIET_MODULES)
    p.add_argument("--dpi", type=int, default=300, help="print sheet resolution")
    p.add_argument("--no-sheets", action="store_true",
                   help="skip printable per-target sheets")
    args = p.parse_args()

    rows = read_targets(args.csv)
    n_targets = len(rows)
    n_markers = ac.MARKERS_PER_TARGET * n_targets
    dict_size = max(ac.DEFAULT_DICT_SIZE, n_markers)
    dictionary = ac.make_dictionary(args.dict_bits, dict_size, args.dict_seed)

    off = (args.offset_x, args.offset_y, args.offset_z)
    if args.center:
        ys = [r["y"] for r in rows]
        off = (off[0], off[1] - 0.5 * (min(ys) + max(ys)), off[2])

    # 1) footstep pillar/platform/ground block (reuse gen_footstep_scene logic;
    #    center_y handled above so both blocks share identical offsets)
    geom_block, z_ground, z_min = build_footsteps(
        rows, args.shape, args.size, off, center_y=False,
        plane_margin=args.plane_margin,
        platform_size=tuple(args.platform_size),
        platform_top=args.platform_top)

    # 2) marker textures + geoms
    xml_dir = os.path.dirname(os.path.abspath(args.xml))
    tex_dir = os.path.join(xml_dir, "aruco_markers")
    tex_scale = write_marker_textures(dictionary, n_targets, tex_dir,
                                      args.quiet_modules, args.dict_bits)
    marker_geoms = build_marker_geoms(rows, off, args.marker_size,
                                      args.marker_spread, tex_scale)
    geom_block = geom_block.replace(f"\n    {END_MARK}",
                                    f"\n{marker_geoms}\n    {END_MARK}")
    asset_block = build_marker_assets(n_markers, "aruco_markers")

    # 3) inject into scene XML
    with open(args.xml) as f:
        xml_text = f.read()
    xml_text = strip_start_platform(xml_text)
    xml_text = inject(xml_text, geom_block)                      # worldbody
    xml_text = inject_region(xml_text, asset_block, ASSET_BEGIN,  # assets
                             ASSET_END, "</asset>")
    with open(args.xml, "w") as f:
        f.write(xml_text)

    # 4) board metadata (world pose = footstep top-surface center + yaw)
    targets_meta = [
        {"index": i, "foot": r["foot"],
         "world": {"x": r["x"] + off[0], "y": r["y"] + off[1],
                   "z": r["z"] + off[2], "yaw": r["yaw"]}}
        for i, r in enumerate(rows)
    ]
    ac.save_board(args.board, targets_meta, args.dict_bits, dict_size,
                  args.dict_seed, args.marker_size, args.marker_spread,
                  args.quiet_modules)

    # 5) printable sheets
    if not args.no_sheets:
        write_print_sheets(dictionary, rows, tex_dir, args.marker_size,
                           args.marker_spread, args.quiet_modules,
                           args.dict_bits, args.dpi)

    print(f"Wrote {n_targets} {args.shape} footstep targets + {n_markers} "
          f"ArUco markers into {args.xml}")
    print(f"  textures/sheets : {tex_dir}")
    print(f"  board metadata  : {args.board}")
