#!/usr/bin/env python3
# Copyright (c) 2025, DYROS.
#
# Read absolute world-frame foot targets (config/footcommands_global.csv) and
# write one stepping-stone geom per footstep into a MuJoCo scene XML, so the
# planned footholds can be visualized / stepped on in simulation.
#
# Each foothold is a vertical box (default) or cylinder from the ground plane up
# to the stone top. Boxes show yaw-aligned rectangular footprints; cylinders are
# round pillars (yaw is ignored visually).
#
# Offsets (--offset-x/y/z) apply only to stepping stones:
#   stone XY = CSV target + R(yaw)*(ox, oy)   # foot yaw frame: +x fwd, +y left
#   stone Z  = CSV pos_z + oz                 # world-up
# Collision-free spheres stay on the raw CSV targets (L=red, R=blue).
#
# The geoms are written into a marked region of the XML and the script is
# idempotent: re-running strips every prior auto-generated region (footstep /
# rocky / aruco assets) and aruco side-files, then writes a fresh block.
# Existing hand-authored geoms are left untouched.
#
# Frame note:
#   footcommands_global.csv is in the real world frame (its initial stance foot is
#   anchored at the spawn foot pose, matching deploy.yaml global_init_*foot), so the
#   targets already line up with the MuJoCo scene. When min(pos_z) is below the
#   spawn platform top, start_platform spans down to that level and footstep_ground
#   sits there. If min(pos_z) is at/above platform top, footstep_ground moves to
#   the platform top and start_platform uses a fixed depth.
#
# Usage:
#   python3 cmd/gen_footstep_scene.py
#   python3 cmd/gen_footstep_scene.py --size 0.12 0.07 --offset-y 0.0
#   python3 cmd/gen_footstep_scene.py --csv config/footcommands_global.csv \
#       --xml ../unitree_mujoco/unitree_robots/g1/scene_29dof_footstep.xml

import argparse
import csv
import math
import os
import re
import shutil

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJ_DIR = os.path.dirname(_THIS_DIR)
_WS_DIR = os.path.dirname(_PROJ_DIR)
DEFAULT_CSV = os.path.join(_PROJ_DIR, "config", "footcommands_global.csv")
DEFAULT_XML = os.path.join(
    _WS_DIR, "unitree_mujoco", "unitree_robots", "g1", "scene_29dof_footstep.xml"
)

BEGIN_MARK = "<!-- BEGIN footstep geoms (auto-generated by gen_footstep_scene.py) -->"
END_MARK = "<!-- END footstep geoms -->"

# Every auto-generated region written by gen_footstep_scene /
# gen_rocky_mountain / gen_aruco_footstep_scene / gen_shatters_obstacles.
# Each script strips all of these before injecting its own block so they
# never stack in the same XML.
ALL_GENERATED_REGIONS = [
    (BEGIN_MARK, END_MARK),
    ("<!-- BEGIN footstep cubes (auto-generated by gen_footstep_scene.py) -->",
     "<!-- END footstep cubes -->"),
    ("<!-- BEGIN rocky mountain geoms (auto-generated by gen_rocky_mountain.py) -->",
     "<!-- END rocky mountain geoms -->"),
    ("<!-- BEGIN aruco marker assets (auto-generated by gen_aruco_footstep_scene.py) -->",
     "<!-- END aruco marker assets -->"),
    ("<!-- BEGIN shatter obstacles (auto-generated by gen_shatters_obstacles.py) -->",
     "<!-- END shatter obstacles -->"),
]

DEFAULT_BOARD = os.path.join(_PROJ_DIR, "config", "aruco_board.json")

# rgba per swing foot (stepping stones)
# COLOR_R = "0.80 0.30 0.30 1"  # right foot
# COLOR_L = "0.30 0.45 0.80 1"  # left foot

COLOR_R = "0.4 0.3 0.5 1"  # right foot
# COLOR_R = "0.45 0.28 0.12 1"  # right foot (brown)
COLOR_L = COLOR_R  # left foot
COLOR_GROUND = "0.7 0.6 0.5 1"
COLOR_PLATFORM = COLOR_R
COLOR_TARGET_L = "0.9 0.15 0.15 1"   # left foot target: red
COLOR_TARGET_R = "0.15 0.35 0.95 1"  # right foot target: blue
DEFAULT_PLATFORM_SIZE = (0.1, 0.17)
DEFAULT_PLATFORM_TOP = 0.0
DEFAULT_PLATFORM_HALF_HEIGHT = 0.5  # when min(pos_z) >= platform_top
DEFAULT_MARKER_RADIUS = 0.025

def read_targets(path):
    with open(path, newline="") as f:
        reader = csv.reader(f)
        header = [h.strip().lower() for h in next(reader)]
        idx = {name: i for i, name in enumerate(header)}
        for c in ["foot", "pos_x", "pos_y", "pos_z", "yaw"]:
            if c not in idx:
                raise ValueError(f"missing required column '{c}' in {path}")
        rows = []
        for cells in reader:
            cells = [c.strip() for c in cells]
            if not cells or all(c == "" for c in cells):
                continue
            foot = cells[idx["foot"]].strip().lower()
            rows.append({
                "foot": "R" if foot in ("r", "right") else "L",
                "x": float(cells[idx["pos_x"]]),
                "y": float(cells[idx["pos_y"]]),
                "z": float(cells[idx["pos_z"]]),
                "yaw": float(cells[idx["yaw"]]),
            })
    if not rows:
        raise ValueError(f"no data rows in {path}")
    return rows


def yaw_to_quat(yaw):
    return (math.cos(yaw / 2.0), 0.0, 0.0, math.sin(yaw / 2.0))


def yaw_frame_offset(x, y, yaw, ox, oy):
    """Translate (x, y) by (ox, oy) in the foot yaw frame (+x fwd, +y left)."""
    c, s = math.cos(yaw), math.sin(yaw)
    return x + c * ox - s * oy, y + s * ox + c * oy


def prepare_rows(rows, center_y=False):
    """Copy rows; optionally recenter world-y so the path straddles y=0."""
    work = [dict(r) for r in rows]
    if center_y:
        ys = [r["y"] for r in work]
        dy = -0.5 * (min(ys) + max(ys))
        for r in work:
            r["y"] += dy
    return work


def stone_landing_poses(rows, off, stair=False):
    """Stepping-stone landings: XY in each foot's yaw frame, Z world-up.

    Returns list of dicts: sx, sy, sz, yaw, foot (CSV x/y/z untouched).
    If `stair`, stone world-y is forced to 0 so left/right treads stack on
    the same lateral line (a staircase); spheres and ArUco still use CSV y.
    """
    ox, oy, oz = off
    out = []
    for r in rows:
        sx, sy = yaw_frame_offset(r["x"], r["y"], r["yaw"], ox, oy)
        if stair:
            sy = 0.0
        out.append({
            "sx": sx, "sy": sy, "sz": r["z"] + oz,
            "yaw": r["yaw"], "foot": r["foot"],
        })
    return out


def build_footsteps(rows, shape, size_xy, off, center_y, plane_margin,
                    platform_size, platform_top, marker_radius=DEFAULT_MARKER_RADIUS,
                    stair=False):
    """Build spawn platform, ground plane, stepping geoms, and target spheres.

    size_xy: (HX, HY) or (HX, HY, HZ). HX/HY are horizontal half-extents [m]
    (cylinder uses HX as radius). If HZ is given, it is the vertical half-size
    and the geom top face stays at the stone top; otherwise height is
    stone_top - ground.

    Stones use yaw-frame XY offset from `off`; spheres stay on CSV targets.
    If center_y, both are recentered in world y first (same lateral shift).
    If stair, stone world-y is 0 (cubes share a lateral line); spheres keep CSV y.
    """
    if len(size_xy) == 3:
        sx, sy, fixed_hz = size_xy
    elif len(size_xy) == 2:
        sx, sy = size_xy
        fixed_hz = None
    else:
        raise ValueError(f"size must be HX HY [HZ], got {len(size_xy)} values")
    radius = sx
    plat_hx, plat_hy = platform_size

    work = prepare_rows(rows, center_y)
    stones = stone_landing_poses(work, off, stair=stair)
    zs_top = [s["sz"] for s in stones]
    z_min = min(zs_top)

    if z_min >= platform_top:
        z_ground = platform_top
        plat_hz = DEFAULT_PLATFORM_HALF_HEIGHT
        plat_zc = platform_top - plat_hz
    else:
        z_ground = z_min
        plat_hz = (platform_top - z_min) * 0.5
        plat_zc = z_min + plat_hz

    xs = [s["sx"] for s in stones]
    ys = [s["sy"] for s in stones]
    plane_cx = 0.5 * (min(xs) + max(xs))
    plane_cy = 0.5 * (min(ys) + max(ys))
    plane_hx = 0.5 * (max(xs) - min(xs)) + plane_margin
    plane_hy = 0.5 * (max(ys) - min(ys)) + plane_margin

    lines = [
        f'    <geom name="start_platform" type="box" group="3"'
        f'size="{plat_hx:.4f} {plat_hy:.4f} {plat_hz:.4f}" '
        f'pos="0 0 {plat_zc:.4f}" '
        f'rgba="{COLOR_PLATFORM}"/>',
        f'    <geom name="footstep_ground" type="plane" '
        f'pos="{plane_cx:.4f} {plane_cy:.4f} {z_ground:.4f}" '
        f'size="{plane_hx:.4f} {plane_hy:.4f} 0.1" '
        f'rgba="{COLOR_GROUND}" material="MatPlane2" group="2"/>',
    ]

    for i, s in enumerate(stones):
        x, y, z_top = s["sx"], s["sy"], s["sz"]
        if fixed_hz is not None:
            hz = fixed_hz
            zc = z_top - hz  # top face at stone top
        else:
            height = z_top - z_ground
            if height < 1e-4:
                continue  # foothold sits on the ground plane; no pillar needed
            hz = height * 0.5
            zc = z_ground + hz
        qw, qx, qy, qz = yaw_to_quat(s["yaw"])
        color = COLOR_R if s["foot"] == "R" else COLOR_L
        if shape == "cylinder":
            lines.append(
                f'    <geom name="footstep_cyl_{i:02d}" type="cylinder" group="3"'
                f'size="{radius:.4f} {hz:.4f}" '
                f'pos="{x:.4f} {y:.4f} {zc:.4f}" '
                f'rgba="{color}"/>'
            )
        else:
            lines.append(
                f'    <geom name="footstep_box_{i:02d}" type="box" group="3"'
                f'size="{sx:.4f} {sy:.4f} {hz:.4f}" '
                f'pos="{x:.4f} {y:.4f} {zc:.4f}" '
                f'quat="{qw:.6f} {qx:.6f} {qy:.6f} {qz:.6f}" '
                f'rgba="{color}"/>'
            )

    # Spheres at CSV targets (after optional center_y; no stone offset)
    rad = marker_radius
    for i, r in enumerate(work):
        x, y, z = r["x"], r["y"], r["z"] + rad
        color = COLOR_TARGET_L if r["foot"] == "L" else COLOR_TARGET_R
        lines.append(
            f'    <geom name="target_{r["foot"]}_{i:02d}" type="sphere" group="5" '
            f'size="{rad:.4f}" pos="{x:.4f} {y:.4f} {z:.4f}" '
            f'rgba="{color}" contype="0" conaffinity="0"/>'
        )

    return f"    {BEGIN_MARK}\n" + "\n".join(lines) + f"\n    {END_MARK}", z_ground, z_min


def strip_generated_regions(xml_text, regions=None):
    """Remove every marked auto-generated region (all three scene generators)."""
    if regions is None:
        regions = ALL_GENERATED_REGIONS
    for begin, end in regions:
        while True:
            b = xml_text.find(begin)
            e = xml_text.find(end)
            if b == -1 or e == -1 or e < b:
                break
            line_start = xml_text.rfind("\n", 0, b) + 1
            end_after = e + len(end)
            if end_after < len(xml_text) and xml_text[end_after] == "\n":
                end_after += 1
            xml_text = xml_text[:line_start] + xml_text[end_after:]
    return xml_text


def clear_aruco_artifacts(xml_path, board_path=None):
    """Remove textures/sheets/PDF and board JSON left by gen_aruco_footstep_scene."""
    xml_dir = os.path.dirname(os.path.abspath(xml_path))
    tex_dir = os.path.join(xml_dir, "aruco_markers")
    if os.path.isdir(tex_dir):
        shutil.rmtree(tex_dir)
    if board_path is None:
        board_path = DEFAULT_BOARD
    if board_path and os.path.isfile(board_path):
        os.remove(board_path)


def strip_start_platform(xml_text):
    """Remove hand-authored start_platform so the generated block owns it."""
    xml_text = re.sub(
        r'\n\s*<!-- start platform:.*?-->\s*\n',
        '\n',
        xml_text,
        count=1,
    )
    xml_text = re.sub(
        r'\n\s*<geom name="start_platform"[^/]*/>\s*\n',
        '\n',
        xml_text,
        count=1,
    )
    return xml_text


def inject(xml_text, block):
    """Strip all prior generator regions, then insert block before </worldbody>."""
    xml_text = strip_generated_regions(xml_text)
    close = xml_text.rfind("</worldbody>")
    if close == -1:
        raise ValueError("no </worldbody> found in scene XML")
    line_start = xml_text.rfind("\n", 0, close) + 1
    return xml_text[:line_start] + block + "\n" + xml_text[line_start:]


if __name__ == "__main__":
    p = argparse.ArgumentParser(description="Generate footstep geoms in a MuJoCo scene XML.")
    p.add_argument("--csv", default=DEFAULT_CSV, help="footcommands_global.csv path")
    p.add_argument("--xml", default=DEFAULT_XML, help="MuJoCo scene XML to edit")
    p.add_argument("--shape", choices=["box", "cylinder"], default="box",
                   help="box: yaw-aligned rectangle (default); cylinder: round pillar")
    p.add_argument("--size", nargs="+", type=float, default=[0.1, 0.1, 0.05],
    # p.add_argument("--size", nargs="+", type=float, default=[0.125, 0.07, 0.05],
                   metavar="H",
                   help="HX HY [HZ]: box half-extents [m] (cylinder: radius=HX, HY ignored). "
                        "If HZ given, vertical half-size is fixed (top at pos_z); "
                        "otherwise height is from ground to pos_z")
    p.add_argument("--plane-margin", type=float, default=3.0,
                   help="extra half-length added around the footstep bounding box for the ground plane [m]")
    p.add_argument("--platform-size", nargs=2, type=float,
                   default=list(DEFAULT_PLATFORM_SIZE), metavar=("HX", "HY"),
                   help="spawn platform horizontal half-extents [m]")
    p.add_argument("--platform-top", type=float, default=DEFAULT_PLATFORM_TOP,
                   help="spawn platform top face height [m] (default: z=0)")
    p.add_argument("--offset-x", type=float, default=0.035,
                   help="stone XY offset in each foot's yaw frame, forward [m] "
                        "(spheres stay on CSV)")
    p.add_argument("--offset-y", type=float, default=0.0,
                   help="stone XY offset in each foot's yaw frame, left [m]")
    p.add_argument("--offset-z", type=float, default=-0.035,
                   help="stone top height offset in world-up [m]")
    p.add_argument("--marker-radius", type=float, default=DEFAULT_MARKER_RADIUS,
                   help="foot-target sphere radius [m] (left red, right blue)")
    p.add_argument("--center", action="store_true",
                   help="re-center the lateral (y) span on y=0 (off by default; the "
                        "CSV is already in the real world frame)")
    args = p.parse_args()
    if len(args.size) not in (2, 3):
        p.error("--size expects HX HY [HZ] (2 or 3 values)")

    rows = read_targets(args.csv)
    block, z_ground, z_min = build_footsteps(rows, args.shape, args.size,
                            (args.offset_x, args.offset_y, args.offset_z),
                            center_y=args.center,
                            plane_margin=args.plane_margin,
                            platform_size=tuple(args.platform_size),
                            platform_top=args.platform_top,
                            marker_radius=args.marker_radius)

    with open(args.xml) as f:
        xml_text = f.read()
    xml_text = strip_start_platform(xml_text)
    clear_aruco_artifacts(args.xml)
    with open(args.xml, "w") as f:
        f.write(inject(xml_text, block))

    ground_note = (
        f"at platform_top={args.platform_top:.4f} (min pos_z={z_min:.4f} >= platform)"
        if z_min >= args.platform_top
        else f"z_ground={z_ground:.4f}"
    )
    print(f"Wrote start_platform + ground plane + {len(rows)} {args.shape} "
          f"footsteps + {len(rows)} target markers "
          f"(L=red, R=blue) into {args.xml} ({ground_note})")
