#!/usr/bin/env python3
# Copyright (c) 2025, DYROS.
#
# Read absolute world-frame foot targets (config/footcommands_global.csv) and
# write a "rocky mountain" terrain into a MuJoCo scene XML: instead of isolated
# stepping-stone pillars, the space between footholds is filled with a dense
# field of rock-colored columns whose heights are interpolated from the footstep
# heights, so the whole path looks like one continuous mountain climb.
#
# Layers generated (all inside one marked, idempotent region):
#   1. start_platform      - spawn platform under the robot (same as before)
#   2. footstep_ground     - large ground plane at the lowest terrain level
#   3. rock_XXXX           - columns forming the mountain body, either boxes
#                            (--rock-shape box, yaw-jittered) or cylinders
#                            (--rock-shape cylinder, basalt-like), on a square
#                            or hexagonal lattice (--layout). The ground behind
#                            the spawn point is left bare out to --start-clear so
#                            the robot starts on the platform rather than inside
#                            the rocks, while the rock ahead of it (where it
#                            actually walks) is untouched.
#                            Cells within --flush-radius of a stepping stone are
#                            set to exactly that stone's landing height (minus a
#                            2 mm anti-z-fighting drop), so the stones blend
#                            flush into the surrounding rock. Beyond that, cell
#                            tops fade over --flush-blend to `clearance` below
#                            the interpolated footstep surface so the filler
#                            terrain never obstructs the swing foot.
#   4. stone_XX            - stepping stones the robot lands on. Their XY is the
#                            CSV target shifted by --offset-x/y in that foot's
#                            yaw frame (forward=x, left=y); Z uses --offset-z in
#                            world up. Boxes are yaw-aligned; cylinders ignore yaw.
#   5. target_L_XX/R_XX    - collision-free spheres at the raw CSV target
#                            (no offset): LEFT = red, RIGHT = blue
#
# The terrain only fills a corridor around the footstep path (distance-to-path
# falloff), so it reads as a mountain ridge rather than a filled field.
# Deterministic per-cell noise + color variation give a natural rocky look.
#
# Column geometry is two independent numbers: --spacing is how far apart the
# columns sit, --rock-width is how wide each one is. Making the width larger than
# the spacing overlaps neighbors and hides the seams. (--overlap is the older
# relative way to say the same thing: width = spacing * overlap.)
#
# Round columns do not tile a square lattice, so the width must exceed the
# spacing by 1.414x (grid) or 1.155x (hex) or gaps open up between neighbors.
# The script computes that threshold and warns, in millimeters, when the chosen
# width is under it.
#
# Idempotent: re-running strips every prior auto-generated region (footstep /
# rocky / aruco assets) and aruco side-files, then writes a fresh block, so the
# three scene generators never stack on the same XML.
#
# Usage:
#   python3 cmd/gen_rocky_mountain.py
#   python3 cmd/gen_rocky_mountain.py --spacing 0.15 --rock-width 0.18
#   python3 cmd/gen_rocky_mountain.py --spacing 0.10 --rock-width 0.13 --clearance 0.03
#   python3 cmd/gen_rocky_mountain.py --rock-shape cylinder --layout hex \
#       --spacing 0.14 --rock-width 0.17
#   python3 cmd/gen_rocky_mountain.py --rock-shape cylinder --stone-shape cylinder
#   python3 cmd/gen_rocky_mountain.py --csv config/footcommands_global.csv \
#       --xml ../unitree_mujoco/unitree_robots/g1/scene_29dof_footstep.xml

import argparse
import csv
import math
import os
import re
import sys

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _THIS_DIR)
from gen_footstep_scene import clear_aruco_artifacts, inject as _inject_shared

_PROJ_DIR = os.path.dirname(_THIS_DIR)
_WS_DIR = os.path.dirname(_PROJ_DIR)
DEFAULT_CSV = os.path.join(_PROJ_DIR, "config", "footcommands_global.csv")
DEFAULT_XML = os.path.join(
    _WS_DIR, "unitree_mujoco", "unitree_robots", "g1", "scene_29dof_footstep.xml"
)

BEGIN_MARK = "<!-- BEGIN rocky mountain geoms (auto-generated by gen_rocky_mountain.py) -->"
END_MARK = "<!-- END rocky mountain geoms -->"

COLOR_STONE = "0.6 0.5 0.4 1"
# COLOR_STONE = "0.7 0.6 0.5 1"
# COLOR_GROUND = "0.7 0.6 0.5 1"
COLOR_GROUND = "0.3 0.3 0.3 1"
COLOR_PLATFORM = COLOR_STONE
COLOR_TARGET_L = "0.9 0.15 0.15 1"   # left foot target: red
COLOR_TARGET_R = "0.15 0.35 0.95 1"  # right foot target: blue
ROCK_BASE_RGB = (0.6, 0.5, 0.4)
# ROCK_BASE_RGB = (0.48, 0.44, 0.40)   # brown-gray rock

DEFAULT_PLATFORM_SIZE = (0.12, 0.17)
DEFAULT_PLATFORM_TOP = 0.0
DEFAULT_PLATFORM_HALF_HEIGHT = 0.5  # when min terrain z >= platform_top


# ---------------------------------------------------------------------------
# input
# ---------------------------------------------------------------------------

def read_targets(path):
    with open(path, newline="") as f:
        reader = csv.reader(f)
        header = [h.strip().lower() for h in next(reader)]
        idx = {name: i for i, name in enumerate(header)}
        for c in ["foot", "pos_x", "pos_y", "pos_z", "yaw"]:
            if c not in idx:
                raise ValueError(f"missing required column '{c}' in {path}")
        rows = []
        for cells in reader:
            cells = [c.strip() for c in cells]
            if not cells or all(c == "" for c in cells):
                continue
            foot = cells[idx["foot"]].strip().lower()
            rows.append({
                "foot": "R" if foot in ("r", "right") else "L",
                "x": float(cells[idx["pos_x"]]),
                "y": float(cells[idx["pos_y"]]),
                "z": float(cells[idx["pos_z"]]),
                "yaw": float(cells[idx["yaw"]]),
            })
    if not rows:
        raise ValueError(f"no data rows in {path}")
    return rows


def yaw_to_quat(yaw):
    return (math.cos(yaw / 2.0), 0.0, 0.0, math.sin(yaw / 2.0))


def yaw_frame_offset(x, y, yaw, ox, oy):
    """Translate (x, y) by (ox, oy) expressed in the foot yaw frame.

    Foot frame: +x forward along yaw, +y left. World = R(yaw) * local.
    """
    c, s = math.cos(yaw), math.sin(yaw)
    return x + c * ox - s * oy, y + s * ox + c * oy


def stone_landing_poses(rows, off):
    """Stepping-stone landings: XY offset in each foot's yaw frame, Z world-up.

    Returns list of dicts with keys sx, sy, sz, yaw, foot (CSV x/y/z untouched).
    """
    ox, oy, oz = off
    out = []
    for r in rows:
        sx, sy = yaw_frame_offset(r["x"], r["y"], r["yaw"], ox, oy)
        out.append({
            "sx": sx, "sy": sy, "sz": r["z"] + oz,
            "yaw": r["yaw"], "foot": r["foot"],
        })
    return out



# ---------------------------------------------------------------------------
# deterministic per-cell noise (order-independent, no RNG state)
# ---------------------------------------------------------------------------

def cell_hash(i, j, seed, salt=0.0):
    """Deterministic pseudo-random value in [0, 1) for grid cell (i, j)."""
    v = math.sin(i * 12.9898 + j * 78.233 + seed * 37.719 + salt * 4.581) * 43758.5453
    return v - math.floor(v)


def rock_rgba(top, z_lo, z_span, i, j, seed, salt=2.0):
    """Height-shaded rock color with per-cell variation → 'rgba=\"...\"'."""
    rel = (top - z_lo) / z_span
    shade = 0.72 + 0.38 * max(0.0, min(1.0, rel))
    var = (cell_hash(i, j, seed, salt=salt) - 0.5) * 0.12
    r = max(0.0, min(1.0, (ROCK_BASE_RGB[0] + var) * shade))
    g = max(0.0, min(1.0, (ROCK_BASE_RGB[1] + var * 0.9) * shade))
    b = max(0.0, min(1.0, (ROCK_BASE_RGB[2] + var * 0.8) * shade))
    return f'rgba="{r:.3f} {g:.3f} {b:.3f} 1"'


# ---------------------------------------------------------------------------
# geometry helpers
# ---------------------------------------------------------------------------

def point_segment_dist(px, py, ax, ay, bx, by):
    """2D distance from point P to segment AB."""
    abx, aby = bx - ax, by - ay
    apx, apy = px - ax, py - ay
    ab2 = abx * abx + aby * aby
    if ab2 < 1e-12:
        return math.hypot(apx, apy)
    t = max(0.0, min(1.0, (apx * abx + apy * aby) / ab2))
    return math.hypot(px - (ax + t * abx), py - (ay + t * aby))


def path_distance(px, py, path):
    """Min 2D distance from (px, py) to the footstep polyline."""
    d = float("inf")
    for k in range(len(path) - 1):
        d = min(d, point_segment_dist(px, py,
                                      path[k][0], path[k][1],
                                      path[k + 1][0], path[k + 1][1]))
    return d


def idw_height(px, py, points, power=2.0, eps=0.02):
    """Inverse-distance-weighted surface height at (px, py).

    points: list of (x, y, z). eps keeps weights finite on top of a point.
    """
    wsum = 0.0
    zsum = 0.0
    for (x, y, z) in points:
        d2 = (px - x) ** 2 + (py - y) ** 2 + eps * eps
        w = 1.0 / (d2 ** (power / 2.0))
        wsum += w
        zsum += w * z
    return zsum / wsum


# ---------------------------------------------------------------------------
# column lattice & gap-free coverage
# ---------------------------------------------------------------------------

HEX_ROW_DY = math.sqrt(3.0) / 2.0  # triangular-lattice row pitch, in cell units


def lattice_cells(x0, y0, x1, y1, cell, layout):
    """Yield (i, j, cx, cy) column centers covering the [x0,x1]x[y0,y1] box.

    'grid' is a square lattice; 'hex' staggers alternate rows by half a cell and
    tightens row spacing to sqrt(3)/2, giving the tighter triangular packing that
    round columns need to avoid gaps.
    """
    row_dy = cell * (HEX_ROW_DY if layout == "hex" else 1.0)
    nx = max(1, int(math.ceil((x1 - x0) / cell)) + (1 if layout == "hex" else 0))
    ny = max(1, int(math.ceil((y1 - y0) / row_dy)))
    for j in range(ny):
        cy = y0 + (j + 0.5) * row_dy
        x_off = 0.5 * cell if (layout == "hex" and j % 2) else 0.0
        for i in range(nx):
            yield i, j, x0 + (i + 0.5) * cell + x_off, cy


def column_width(args):
    """Effective rock column width [m]: box edge-to-edge, or cylinder diameter.

    --rock-width sets it outright; otherwise it is --spacing scaled by --overlap.
    """
    if args.rock_width is not None:
        return args.rock_width
    return args.spacing * args.overlap


def required_width(shape, layout, spacing):
    """Narrowest gap-free column width [m] for a lattice at this spacing."""
    return spacing * required_overlap(shape, layout)


def required_overlap(shape, layout):
    """Smallest --overlap that leaves no gaps between neighboring columns.

    A column's reach is `half` = 0.5*cell*overlap. The worst-covered point of a
    square lattice is a cell corner at cell/sqrt(2); of a triangular lattice, a
    triangle circumcenter at cell/sqrt(3). A cylinder reaches exactly `half` in
    every direction, so below the returned value every one of those points is
    deterministically bare.

    Boxes are not held to this. They reach `half` only at their edge midpoints
    but sqrt(2)*half at their corners, each corner point is covered if any one
    of the four columns around it reaches, and --max-cell-yaw randomizes which
    way each one points. Axis-aligned boxes tile each axis independently, so 1.0
    seals; yaw-jittered boxes can open occasional pinholes above that, which is
    what --overlap 1.25 already absorbs.
    """
    if shape == "box":
        return 1.0
    return 2.0 / math.sqrt(3.0) if layout == "hex" else math.sqrt(2.0)


# ---------------------------------------------------------------------------
# terrain generation
# ---------------------------------------------------------------------------

def build_rock_cells(stones, args, z_ground):
    """Lattice of columns approximating a rocky mountain under the footsteps.

    `stones` is from stone_landing_poses() (yaw-frame XY offset already applied).
    Columns are boxes or cylinders (args.rock_shape) on a square or triangular
    lattice (args.layout). Returns a list of XML geom lines.
    """
    # surface control points: stone landings + a virtual start point so the
    # terrain descends smoothly onto the spawn platform
    stone_xyz = [(s["sx"], s["sy"], s["sz"]) for s in stones]
    points = [(0.0, 0.0, args.platform_top)] + stone_xyz
    path = [(p[0], p[1]) for p in points]

    xs = [p[0] for p in points]
    ys = [p[1] for p in points]
    zs = [p[2] for p in points]
    z_lo, z_hi = min(zs), max(zs)
    z_span = max(z_hi - z_lo, 1e-6)

    cell = args.spacing
    # a column's inscribed reach: box half-extent, or cylinder radius
    half = 0.5 * column_width(args)
    margin = args.terrain_margin
    x0, x1 = min(xs) - margin, max(xs) + margin
    y0, y1 = min(ys) - margin, max(ys) + margin

    w0, w1 = args.corridor  # full-height / zero-height distances from the path
    lines = []
    n_cells = 0
    # farthest a column reaches from its own center: a box corner, or the radius
    reach = half * math.sqrt(2.0) if args.rock_shape == "box" else half
    start_keep_out = args.start_clear + reach

    for i, j, cx, cy in lattice_cells(x0, y0, x1, y1, cell, args.layout):
        # keep the ground behind the spawn point bare: the robot faces +x and
        # only ever walks forward, so rock there is clutter it could spawn
        # inside. Columns from --start-clear-front onward are kept, which is
        # what the robot steps onto. `reach` makes the radius hold for any yaw.
        if (args.start_clear > 0.0
                and cx < args.start_clear_front
                and math.hypot(cx, cy) < start_keep_out):
            continue

        d = path_distance(cx, cy, path)
        if d >= w1:
            continue  # outside the mountain corridor
        # 1 inside the corridor core, cosine falloff to 0 at w1
        if d <= w0:
            falloff = 1.0
        else:
            falloff = 0.5 * (1.0 + math.cos(math.pi * (d - w0) / (w1 - w0)))

        z_surf = idw_height(cx, cy, points, power=args.idw_power)
        # far-field surface: below the landing surface, with rocky jitter
        u = cell_hash(i, j, args.seed)
        base_top = z_surf - args.clearance - args.noise * u

        # flush zone: match the landing height of nearby stepping stones
        # exactly (min over all stones in range so a higher neighbor never
        # blocks a lower landing spot); tiny drop avoids z-fighting with
        # the stone's own top face
        r0 = args.flush_radius
        r1 = r0 + args.flush_blend
        z_in = [z for (sx_, sy_, z) in stone_xyz
                if (cx - sx_) ** 2 + (cy - sy_) ** 2 <= r0 * r0]
        if z_in:
            top = min(z_in) - args.flush_drop
        else:
            ds_min, z_near = min(
                (math.hypot(cx - sx_, cy - sy_), z) for (sx_, sy_, z) in stone_xyz)
            if ds_min < r1:
                # cosine blend from flush height back to the far-field surface
                t = 0.5 * (1.0 - math.cos(math.pi * (ds_min - r0) / args.flush_blend))
                top = (1.0 - t) * (z_near - args.flush_drop) + t * base_top
            else:
                top = base_top
        # taper toward the ground away from the path
        top = z_ground + (top - z_ground) * falloff

        h = top - z_ground
        if h < args.min_height:
            continue
        n_cells += 1

        hz = 0.5 * h
        zc = z_ground + hz

        # color: height-shaded rock with per-cell variation
        rgba = rock_rgba(top, z_lo, z_span, i, j, args.seed)

        if args.rock_shape == "cylinder":
            # rotationally symmetric about z, so a yaw quat would be a no-op
            lines.append(
                f'    <geom name="rock_{n_cells:04d}" type="cylinder" '
                f'size="{half:.4f} {hz:.4f}" '
                f'pos="{cx:.4f} {cy:.4f} {zc:.4f}" {rgba}/>'
            )
        else:
            # small random yaw makes the lattice read as tumbled rock
            yaw = (cell_hash(i, j, args.seed, salt=1.0) - 0.5) * 2.0 * args.max_cell_yaw
            qw, qx, qy, qz = yaw_to_quat(yaw)
            lines.append(
                f'    <geom name="rock_{n_cells:04d}" type="box" '
                f'size="{half:.4f} {half:.4f} {hz:.4f}" '
                f'pos="{cx:.4f} {cy:.4f} {zc:.4f}" '
                f'quat="{qw:.6f} {qx:.6f} {qy:.6f} {qz:.6f}" {rgba}/>'
            )
    return lines


# ---------------------------------------------------------------------------
# scene assembly
# ---------------------------------------------------------------------------

def build_scene(rows, off, args):
    # Stones/rocks use yaw-frame XY offset; markers stay on raw CSV targets.
    stones = stone_landing_poses(rows, off)
    zs_top = [s["sz"] for s in stones]
    z_min = min(zs_top)
    platform_top = args.platform_top

    if z_min >= platform_top:
        z_ground = platform_top
        plat_hz = DEFAULT_PLATFORM_HALF_HEIGHT
        plat_zc = platform_top - plat_hz
    else:
        z_ground = z_min
        plat_hz = (platform_top - z_min) * 0.5
        plat_zc = z_min + plat_hz

    xs = [s["sx"] for s in stones]
    ys = [s["sy"] for s in stones]
    plane_cx = 0.5 * (min(xs) + max(xs))
    plane_cy = 0.5 * (min(ys) + max(ys))
    plane_hx = 0.5 * (max(xs) - min(xs)) + args.plane_margin
    plane_hy = 0.5 * (max(ys) - min(ys)) + args.plane_margin

    plat_hx, plat_hy = args.platform_size

    lines = [
        f'    <geom name="start_platform" type="box" '
        f'size="{plat_hx:.4f} {plat_hy:.4f} {plat_hz:.4f}" '
        f'pos="0 0 {plat_zc:.4f}" '
        f'rgba="{COLOR_PLATFORM}"/>',
        f'    <geom name="footstep_ground" type="plane" '
        f'pos="{plane_cx:.4f} {plane_cy:.4f} {z_ground:.4f}" '
        f'size="{plane_hx:.4f} {plane_hy:.4f} 0.1" '
        f'rgba="{COLOR_GROUND}" material="MatPlane2" group="2"/>',
    ]

    # 1) mountain body (follows stone landings, not raw CSV markers)
    rock_lines = build_rock_cells(stones, args, z_ground)
    lines += rock_lines

    # 2) stepping stones (yaw-frame XY offset from CSV target)
    hx, hy = args.stone_size
    z_lo = min(zs_top + [platform_top])
    z_span = max(max(zs_top) - z_lo, 1e-6)
    n_stones = 0
    for i, s in enumerate(stones):
        x, y, z_top = s["sx"], s["sy"], s["sz"]
        height = z_top - z_ground
        if height < 1e-4:
            continue  # sits on the ground plane; no pillar needed
        n_stones += 1
        hz = 0.5 * height
        zc = z_ground + hz
        # same height-shaded + per-stone variation as mountain rock cells
        rgba = rock_rgba(z_top, z_lo, z_span, i, 0, args.seed, salt=3.0)
        if args.stone_shape == "cylinder":
            # round pillar: HX is the radius, HY is unused, yaw has no effect
            lines.append(
                f'    <geom name="stone_{i:02d}" type="cylinder" group="1" '
                f'size="{hx:.4f} {hz:.4f}" '
                f'pos="{x:.4f} {y:.4f} {zc:.4f}" {rgba}/>'
            )
        else:
            qw, qx, qy, qz = yaw_to_quat(s["yaw"])
            lines.append(
                f'    <geom name="stone_{i:02d}" type="box" group="1" '
                f'size="{hx:.4f} {hy:.4f} {hz:.4f}" '
                f'pos="{x:.4f} {y:.4f} {zc:.4f}" '
                f'quat="{qw:.6f} {qx:.6f} {qy:.6f} {qz:.6f}" {rgba}/>'
            )

    # 3) markers at raw CSV targets (no offset) — command / policy goal
    rad = args.marker_radius
    for i, r in enumerate(rows):
        x, y, z = r["x"], r["y"], r["z"] + rad
        color = COLOR_TARGET_L if r["foot"] == "L" else COLOR_TARGET_R
        lines.append(
            f'    <geom name="target_{r["foot"]}_{i:02d}" type="sphere" group="5" '
            f'size="{rad:.4f}" pos="{x:.4f} {y:.4f} {z:.4f}" '
            f'rgba="{color}" contype="0" conaffinity="0"/>'
        )

    block = f"    {BEGIN_MARK}\n" + "\n".join(lines) + f"\n    {END_MARK}"
    return block, z_ground, z_min, len(rock_lines), n_stones


# ---------------------------------------------------------------------------
# XML injection (strips all prior generator regions first)
# ---------------------------------------------------------------------------

def strip_start_platform(xml_text):
    """Remove hand-authored start_platform so the generated block owns it."""
    xml_text = re.sub(
        r'\n\s*<!-- start platform:.*?-->\s*\n',
        '\n',
        xml_text,
        count=1,
    )
    xml_text = re.sub(
        r'\n\s*<geom name="start_platform"[^/]*/>\s*\n',
        '\n',
        xml_text,
        count=1,
    )
    return xml_text


def inject(xml_text, block):
    """Strip footstep/rocky/aruco regions, then insert this script's block."""
    return _inject_shared(xml_text, block)


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    p = argparse.ArgumentParser(
        description="Generate a rocky-mountain footstep terrain in a MuJoCo scene XML.")
    p.add_argument("--csv", default=DEFAULT_CSV, help="footcommands_global.csv path")
    p.add_argument("--xml", default=DEFAULT_XML, help="MuJoCo scene XML to edit")

    t = p.add_argument_group("terrain")
    t.add_argument("--rock-shape", choices=["box", "cylinder"], default="box",
                   help="box: yaw-jittered blocks (default); cylinder: round "
                        "basalt-like columns (yaw has no effect, and they need "
                        "to be wider than the spacing so neighbors still touch)")
    t.add_argument("--layout", choices=["grid", "hex"], default="grid",
                   help="grid: square lattice (default); hex: staggered "
                        "triangular lattice, which packs round columns much "
                        "tighter (needs 1.155x the spacing, not 1.414x)")
    t.add_argument("--spacing", "--cell", type=float, default=0.2,
                   dest="spacing", metavar="M",
                   help="distance between neighboring rock columns [m]")
    t.add_argument("--rock-width", type=float, default=None, metavar="M",
                   help="width of each rock column [m]: box edge-to-edge, or "
                        "cylinder diameter. Set this to size the columns "
                        "directly; leave it out to derive the width from "
                        "--spacing x --overlap instead")
    t.add_argument("--overlap", type=float, default=1.,
                   help="fallback way to size columns when --rock-width is not "
                        "given: width = spacing * overlap. 1.0 makes columns "
                        "exactly meet, >1 overlaps them to hide seams")

    t.add_argument("--start-clear", type=float, default=0.3, metavar="M",
                   help="radius behind the spawn origin kept free of rock "
                        "columns [m], so the robot starts on the bare platform "
                        "instead of in the rocks (0 disables)")
    t.add_argument("--start-clear-front", type=float, default=0.3, metavar="X",
                   help="forward edge of that clear zone [x, m]. The default 0 "
                        "clears only behind the spawn point and leaves the rock "
                        "the robot walks onto intact; raise it to also clear "
                        "ahead, or pass a large value for a full circle")

    t.add_argument("--clearance", type=float, default=0.01,
                   help="how far the filler rock stays below the interpolated "
                        "foot-landing surface [m], outside the flush zones")
    t.add_argument("--flush-radius", type=float, default=0.35,
                   help="rock cells within this distance of a stepping stone "
                        "match its landing height exactly [m]")
    t.add_argument("--flush-blend", type=float, default=0.25,
                   help="transition band from flush height back to the "
                        "clearance surface [m]")
    t.add_argument("--flush-drop", type=float, default=0.002,
                   help="tiny offset below the stone top in flush zones to "
                        "avoid z-fighting [m]")
                        
    t.add_argument("--noise", type=float, default=0.03,
                   help="max downward height jitter per rock column [m]")
    t.add_argument("--max-cell-yaw", type=float, default=1.79,
                   help="max random yaw of each rock column [rad]")
    t.add_argument("--corridor", nargs=2, type=float, default=[0.45, 10.5],
                   metavar=("W0", "W1"),
                   help="distance from the footstep path: full height inside W0, "
                        "tapered to ground at W1 [m]")
    t.add_argument("--terrain-margin", type=float, default=10.8,
                   help="extent of the terrain grid beyond the footstep bounding box [m]")
    t.add_argument("--idw-power", type=float, default=2.0,
                   help="inverse-distance-weighting exponent for the surface")
    t.add_argument("--min-height", type=float, default=0.015,
                   help="rock columns shorter than this are skipped [m]")
    t.add_argument("--seed", type=float, default=7.0,
                   help="seed for the deterministic per-cell noise")

    s = p.add_argument_group("stepping stones & markers")
    s.add_argument("--stone-shape", choices=["box", "cylinder"], default="box",
                   help="box: yaw-aligned rectangular foothold (default); "
                        "cylinder: round pillar of radius HX (yaw ignored)")
    s.add_argument("--stone-size", nargs=2, type=float, default=[0.1, 0.1],
                   metavar=("HX", "HY"),
                   help="stepping-stone half-extents [m] "
                        "(cylinder: radius=HX, HY unused)")
    s.add_argument("--marker-radius", type=float, default=0.025,
                   help="foot-target sphere radius [m] (left red, right blue)")

    g = p.add_argument_group("platform & ground")
    g.add_argument("--plane-margin", type=float, default=1.0,
                   help="extra half-length around the footstep bounding box for the ground plane [m]")
    g.add_argument("--platform-size", nargs=2, type=float,
                   default=list(DEFAULT_PLATFORM_SIZE), metavar=("HX", "HY"),
                   help="spawn platform horizontal half-extents [m]")
    g.add_argument("--platform-top", type=float, default=DEFAULT_PLATFORM_TOP,
                   help="spawn platform top face height [m] (default: z=0)")

    o = p.add_argument_group(
        "offsets (stones/rocks only; spheres stay on CSV targets)")
    o.add_argument("--offset-x", type=float, default=0.0,
                   help="stone XY offset in each foot's yaw frame, forward [m]")
    o.add_argument("--offset-y", type=float, default=0.0,
                   help="stone XY offset in each foot's yaw frame, left [m]")
    o.add_argument("--offset-z", type=float, default=0.0,
                   help="stone top height offset in world-up [m]")

    args = p.parse_args()
    if args.corridor[1] <= args.corridor[0]:
        p.error("--corridor W1 must be greater than W0")

    width = column_width(args)
    if width <= 0.0:
        p.error("rock column width must be positive "
                "(check --rock-width / --overlap)")
    need = required_width(args.rock_shape, args.layout, args.spacing)
    if width < need - 1e-9:
        hint = ""
        if args.layout == "grid":
            hex_need = required_width(args.rock_shape, "hex", args.spacing)
            hint = f", or --layout hex which only needs {1000*hex_need:.0f} mm"
        print(f"warning: {args.rock_shape} columns {1000*width:.0f} mm wide on a "
              f"{1000*args.spacing:.0f} mm {args.layout} lattice leave ~"
              f"{1000*0.5*(need - width):.0f} mm gaps; use "
              f"--rock-width {need:.3f}{hint}")

    rows = read_targets(args.csv)
    off = (args.offset_x, args.offset_y, args.offset_z)
    block, z_ground, z_min, n_rocks, n_stones = build_scene(rows, off, args)

    with open(args.xml) as f:
        xml_text = f.read()
    xml_text = strip_start_platform(xml_text)
    clear_aruco_artifacts(args.xml)
    with open(args.xml, "w") as f:
        f.write(inject(xml_text, block))

    ground_note = (
        f"at platform_top={args.platform_top:.4f} (min pos_z={z_min:.4f} >= platform)"
        if z_min >= args.platform_top
        else f"z_ground={z_ground:.4f}"
    )
    print(f"Rock columns: {args.rock_shape}, {1000*width:.0f} mm wide, "
          f"{1000*args.spacing:.0f} mm apart, {args.layout} lattice")
    print(f"Wrote start_platform + ground plane + {n_rocks} {args.rock_shape} "
          f"rock columns ({args.layout} lattice) + {n_stones} {args.stone_shape} "
          f"stepping stones + {len(rows)} target markers "
          f"into {args.xml} ({ground_note})")
