#!/usr/bin/env python3
# Copyright (c) 2025, DYROS.
#
# Joystick-mode scatter: write a flat 10x10 ground plus randomly placed
# irregular obstacles (shards) into a MuJoCo scene XML. No footstep CSV.
# A 0.5x0.5 box at the origin is left empty so the robot can spawn clear.
#
# Obstacle full-extents are sampled independently per axis from --x/--y/--z.
#
# Usage:
#   python3 cmd/gen_shatters_obstacles.py
#   python3 cmd/gen_shatters_obstacles.py --count 200 --z 0.005 0.03
#   python3 cmd/gen_shatters_obstacles.py --x 0.01 0.03 --y 0.01 0.03 --z 0.005 0.02

import argparse
import math
import os
import random
import sys

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _THIS_DIR)
from gen_footstep_scene import (
    yaw_to_quat, strip_start_platform, inject, clear_aruco_artifacts,
    DEFAULT_XML, COLOR_GROUND,
)

BEGIN_MARK = "<!-- BEGIN shatter obstacles (auto-generated by gen_shatters_obstacles.py) -->"
END_MARK = "<!-- END shatter obstacles -->"

SHARD_BASE_RGB = (0.42, 0.38, 0.34)


def shard_rgba(rng):
    var = (rng.random() - 0.5) * 0.16
    r = max(0.0, min(1.0, SHARD_BASE_RGB[0] + var))
    g = max(0.0, min(1.0, SHARD_BASE_RGB[1] + var * 0.9))
    b = max(0.0, min(1.0, SHARD_BASE_RGB[2] + var * 0.8))
    return f"{r:.3f} {g:.3f} {b:.3f} 1"


def in_start_clear(x, y, clear_xy):
    """True if (x, y) is inside the axis-aligned keep-out box at the origin."""
    hx, hy = 0.5 * clear_xy[0], 0.5 * clear_xy[1]
    return abs(x) < hx and abs(y) < hy


def sample_obstacles(args, rng):
    half_x, half_y = 0.5 * args.ground[0], 0.5 * args.ground[1]
    min_sep2 = args.min_sep * args.min_sep
    placed = []
    lines = []
    attempts = 0
    max_attempts = args.count * 50
    while len(placed) < args.count and attempts < max_attempts:
        attempts += 1
        x = rng.uniform(-half_x, half_x)
        y = rng.uniform(-half_y, half_y)
        if in_start_clear(x, y, args.start_clear):
            continue
        if any((x - qx) ** 2 + (y - qy) ** 2 < min_sep2 for qx, qy in placed):
            continue

        sx = rng.uniform(*args.size_x)
        sy = rng.uniform(*args.size_y)
        sz = rng.uniform(*args.size_z)
        hx, hy, hz = 0.5 * sx, 0.5 * sy, 0.5 * sz
        zc = hz
        rgba = shard_rgba(rng)
        n = len(placed) + 1
        qw, qx, qy, qz = yaw_to_quat(rng.uniform(-math.pi, math.pi))
        lines.append(
            f'    <geom name="shard_{n:04d}" type="box" group="4" '
            f'size="{hx:.4f} {hy:.4f} {hz:.4f}" '
            f'pos="{x:.4f} {y:.4f} {zc:.4f}" '
            f'quat="{qw:.6f} {qx:.6f} {qy:.6f} {qz:.6f}" '
            f'rgba="{rgba}"/>'
        )
        placed.append((x, y))
    return lines


def build_scene(args, rng):
    hx, hy = 0.5 * args.ground[0], 0.5 * args.ground[1]
    lines = [
        f'    <geom name="footstep_ground" type="plane" '
        f'pos="0 0 0" size="{hx:.4f} {hy:.4f} 0.1" '
        f'rgba="{COLOR_GROUND}" material="MatPlane2" group="2"/>',
    ]
    shard_lines = sample_obstacles(args, rng)
    lines += shard_lines
    block = f"    {BEGIN_MARK}\n" + "\n".join(lines) + f"\n    {END_MARK}"
    return block, len(shard_lines)


def _range_pair(name, lo_hi):
    lo, hi = lo_hi
    if lo <= 0.0 or hi <= 0.0:
        raise ValueError(f"--{name} values must be positive")
    if lo > hi:
        raise ValueError(f"--{name} MIN must be <= MAX")
    return lo, hi


if __name__ == "__main__":
    p = argparse.ArgumentParser(
        description="Joystick scatter: flat 10x10 ground with random shards (no CSV)."
    )
    p.add_argument("--xml", default=DEFAULT_XML, help="MuJoCo scene XML to edit")
    p.add_argument("--seed", type=int, default=None, help="RNG seed (default: random)")

    t = p.add_argument_group("obstacles")
    t.add_argument("--x", dest="size_x", nargs=2, type=float, default=[0.1, 0.3],
                   metavar=("MIN", "MAX"), help="obstacle full-size range on X [m]")
    t.add_argument("--y", dest="size_y", nargs=2, type=float, default=[0.1, 0.3],
                   metavar=("MIN", "MAX"), help="obstacle full-size range on Y [m]")
    t.add_argument("--z", dest="size_z", nargs=2, type=float, default=[0.008, 0.03],
                   metavar=("MIN", "MAX"), help="obstacle full-size range on Z [m]")
    t.add_argument("--count", type=int, default=500, help="number of obstacles to place")
    t.add_argument("--min-sep", type=float, default=0.04,
                   help="minimum center-to-center spacing [m]")

    g = p.add_argument_group("ground")
    g.add_argument("--ground", nargs=2, type=float, default=[10.0, 10.0],
                   metavar=("X", "Y"), help="ground plane full size [m]")
    g.add_argument("--start-clear", nargs=2, type=float, default=[0.5, 0.5],
                   metavar=("X", "Y"),
                   help="keep-out box at the origin, full size [m] (no obstacles)")

    args = p.parse_args()
    try:
        args.size_x = _range_pair("x", args.size_x)
        args.size_y = _range_pair("y", args.size_y)
        args.size_z = _range_pair("z", args.size_z)
    except ValueError as e:
        p.error(str(e))
    if args.count <= 0:
        p.error("--count must be positive")
    if args.ground[0] <= 0.0 or args.ground[1] <= 0.0:
        p.error("--ground sizes must be positive")
    if args.start_clear[0] < 0.0 or args.start_clear[1] < 0.0:
        p.error("--start-clear sizes must be non-negative")

    if args.seed is None:
        args.seed = int.from_bytes(os.urandom(4), "little")
    rng = random.Random(args.seed)

    block, n_shards = build_scene(args, rng)

    with open(args.xml) as f:
        xml_text = f.read()
    xml_text = strip_start_platform(xml_text)
    clear_aruco_artifacts(args.xml)
    with open(args.xml, "w") as f:
        f.write(inject(xml_text, block))

    print(f"Wrote {args.ground[0]:.1f}x{args.ground[1]:.1f} ground + {n_shards} shards "
          f"(x={args.size_x}, y={args.size_y}, z={args.size_z}, "
          f"start-clear={tuple(args.start_clear)}, seed={args.seed}) into {args.xml}")
