#!/usr/bin/env python3
# Copyright (c) 2025, DYROS.
#
# Read the goal points the footstep controller walks to
# (deploy.yaml -> footstep.goal.points, command_source: goal) and write them as
# marker geoms into a MuJoCo scene XML, so the goals are visible in simulation.
#
# Each goal becomes a flat disc of radius `reach_radius` (the tolerance the
# planner uses to declare the goal reached) plus a sphere on a short pole at the
# point itself. The markers are visual only: contype/conaffinity are 0 so the
# robot walks straight through them.
#
# Frame note:
#   Goal points are in the world frame anchored at the robot spawn pose
#   (x, y, yaw = 0, 0, 0), which is where the G1 model spawns in the scene, so
#   they line up with the MuJoCo world frame directly.
#
# The geoms are written into a marked region of the XML and the script is
# idempotent: re-running replaces the previously generated region rather than
# appending. On the first run the output scene is seeded from --base.
#
# Usage:
#   python3 cmd/gen_goals.py
#   python3 cmd/gen_goals.py --base scene_29dof_footstep.xml
#
# Then point the simulator at the generated scene:
#   unitree_mujoco/simulate/config.yaml -> robot_scene: "scene_29dof_goals.xml"

import argparse
import math
import os

import yaml

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJ_DIR = os.path.dirname(_THIS_DIR)
_G1_DIR = os.path.join(
    os.path.dirname(_PROJ_DIR), "unitree_mujoco", "unitree_robots", "g1"
)
DEFAULT_CONFIG = os.path.join(_PROJ_DIR, "config", "config.yaml")
DEFAULT_BASE = os.path.join(_G1_DIR, "scene_29dof.xml")
DEFAULT_XML = os.path.join(_G1_DIR, "scene_29dof_goals.xml")

BEGIN_MARK = "<!-- BEGIN goal markers (auto-generated by gen_goals.py) -->"
END_MARK = "<!-- END goal markers -->"

DISC_RGBA = "0.1 0.8 0.2 0.35"
POINT_RGBA = "0.1 0.9 0.2 0.9"
LAST_POINT_RGBA = "0.9 0.5 0.1 0.9"


def resolve_policy_dir(config_path):
    """Mirror param::parser_policy_dir for the Footstep FSM policy_dir."""
    with open(config_path) as f:
        cfg = yaml.safe_load(f)
    policy_dir = cfg["FSM"]["Footstep"]["policy_dir"]
    if not os.path.isabs(policy_dir):
        policy_dir = os.path.join(_PROJ_DIR, policy_dir)

    if not os.path.isdir(os.path.join(policy_dir, "exported")):
        subdirs = sorted(
            os.path.join(policy_dir, d)
            for d in os.listdir(policy_dir)
            if os.path.isdir(os.path.join(policy_dir, d))
        )
        for d in reversed(subdirs):
            if os.path.isdir(os.path.join(d, "exported")):
                return d
    return policy_dir


def read_goals(deploy_path):
    with open(deploy_path) as f:
        deploy = yaml.safe_load(f)
    goal = (deploy.get("footstep") or {}).get("goal")
    if not goal:
        raise ValueError(f"no 'footstep.goal' section in {deploy_path}")
    points = goal.get("points") or []
    if not points:
        raise ValueError(f"'footstep.goal.points' is empty in {deploy_path}")
    out = []
    for i, p in enumerate(points):
        if len(p) < 2:
            raise ValueError(f"goal {i + 1} in {deploy_path} needs [x, y] or [x, y, yaw]")
        # [x, y] leaves the arrival heading free; [x, y, yaw] fixes it.
        yaw = float(p[2]) if len(p) > 2 else None
        out.append((float(p[0]), float(p[1]), yaw))
    reach_radius = float(goal.get("reach_radius", 0.2))
    return out, reach_radius


def build_markers(points, reach_radius, pole_height):
    lines = []
    for i, (x, y, yaw) in enumerate(points):
        rgba = POINT_RGBA if i < len(points) - 1 else LAST_POINT_RGBA
        lines.append(
            f'    <geom name="goal_disc_{i:02d}" type="cylinder" '
            f'size="{reach_radius:.4f} 0.0010" pos="{x:.4f} {y:.4f} 0.0010" '
            f'contype="0" conaffinity="0" group="2" rgba="{DISC_RGBA}"/>'
        )
        lines.append(
            f'    <geom name="goal_pole_{i:02d}" type="capsule" '
            f'size="0.0080 {pole_height * 0.5:.4f}" '
            f'pos="{x:.4f} {y:.4f} {pole_height * 0.5:.4f}" '
            f'contype="0" conaffinity="0" group="2" rgba="{rgba}"/>'
        )
        lines.append(
            f'    <geom name="goal_point_{i:02d}" type="sphere" size="0.0500" '
            f'pos="{x:.4f} {y:.4f} {pole_height:.4f}" '
            f'contype="0" conaffinity="0" group="2" rgba="{rgba}"/>'
        )
        if yaw is None:
            continue  # heading is free for this goal: nothing to draw
        # Arrow from the goal along the arrival heading, lying on the disc.
        length = reach_radius * 1.5
        cx, cy = x + 0.5 * length * math.cos(yaw), y + 0.5 * length * math.sin(yaw)
        tx, ty = x + length * math.cos(yaw), y + length * math.sin(yaw)
        qw, qz = math.cos(yaw / 2.0), math.sin(yaw / 2.0)
        lines.append(
            f'    <geom name="goal_yaw_{i:02d}" type="box" '
            f'size="{length * 0.5:.4f} 0.0150 0.0020" pos="{cx:.4f} {cy:.4f} 0.0030" '
            f'quat="{qw:.6f} 0 0 {qz:.6f}" '
            f'contype="0" conaffinity="0" group="2" rgba="{rgba}"/>'
        )
        lines.append(
            f'    <geom name="goal_yaw_tip_{i:02d}" type="box" '
            f'size="0.0500 0.0500 0.0020" pos="{tx:.4f} {ty:.4f} 0.0030" '
            f'quat="{math.cos((yaw + math.pi / 4) / 2.0):.6f} 0 0 '
            f'{math.sin((yaw + math.pi / 4) / 2.0):.6f}" '
            f'contype="0" conaffinity="0" group="2" rgba="{rgba}"/>'
        )
    return f"    {BEGIN_MARK}\n" + "\n".join(lines) + f"\n    {END_MARK}"


def inject(xml_text, block):
    b = xml_text.find(BEGIN_MARK)
    e = xml_text.find(END_MARK)
    if b != -1 and e != -1:
        line_start = xml_text.rfind("\n", 0, b) + 1
        return xml_text[:line_start] + block + xml_text[e + len(END_MARK):]

    close = xml_text.rfind("</worldbody>")
    if close == -1:
        raise ValueError("no </worldbody> found in scene XML")
    line_start = xml_text.rfind("\n", 0, close) + 1
    return xml_text[:line_start] + block + "\n" + xml_text[line_start:]


if __name__ == "__main__":
    p = argparse.ArgumentParser(
        description="Visualize deploy.yaml footstep goal points in a MuJoCo scene XML."
    )
    p.add_argument("--config", default=DEFAULT_CONFIG,
                   help="g1_controller config.yaml (resolves the Footstep policy dir)")
    p.add_argument("--deploy", default=None,
                   help="deploy.yaml path (default: resolved from --config)")
    p.add_argument("--base", default=DEFAULT_BASE,
                   help="scene XML to seed the output from when it does not exist yet")
    p.add_argument("--xml", default=DEFAULT_XML, help="scene XML to write")
    p.add_argument("--pole-height", type=float, default=0.6,
                   help="height of the goal marker pole [m]")
    args = p.parse_args()

    deploy_path = args.deploy or os.path.join(
        resolve_policy_dir(args.config), "..", "deploy_base.yaml"
    )
    points, reach_radius = read_goals(deploy_path)

    source = args.xml if os.path.exists(args.xml) else args.base
    with open(source) as f:
        xml_text = f.read()
    with open(args.xml, "w") as f:
        f.write(inject(xml_text, build_markers(points, reach_radius, args.pole_height)))

    print(f"Read {len(points)} goal points from {deploy_path}")
    for i, (x, y, yaw) in enumerate(points):
        heading = f"yaw={yaw:.3f} rad ({math.degrees(yaw):.1f} deg)" if yaw is not None \
            else "heading free"
        print(f"  goal {i + 1}: x={x:.3f} y={y:.3f} {heading}")
    print(f"Wrote goal markers (reach_radius={reach_radius:.3f} m) into {args.xml}"
          f"{'' if source == args.xml else f' (seeded from {os.path.basename(args.base)})'}")
    print("Set unitree_mujoco/simulate/config.yaml -> "
          f'robot_scene: "{os.path.basename(args.xml)}" to use it.')
