#!/usr/bin/env python3
# Copyright (c) 2025, DYROS.
#
# Like cmd/gen_footstep_scene.py, but each stepping stone additionally gets
# FOUR ArUco markers (3x3-bit, "3 cm" class) on its top surface so an onboard
# camera (D435i) can estimate the pose precisely (16 corner points per target
# -> robust PnP). Stone XY uses yaw-frame --offset-*; red/blue spheres stay on
# the raw CSV targets. ArUco geoms + board.json follow the stone landings.
#
# Outputs:
#   1. Scene XML edits (same marked region as gen_footstep_scene.py for the
#      geoms + an extra marked region in <asset> for marker textures). All
#      prior generator regions (footstep / rocky / aruco) are stripped first.
#   2. Marker texture PNGs      -> <xml_dir>/aruco_markers/marker_###.png
#   3. Board metadata JSON      -> config/aruco_board.json (read by
#      cmd/aruco_footstep_perception.py to build PnP object points)
#   4. Printable per-target sheets (real world) -> <xml_dir>/aruco_markers/
#      sheet_target_##.png at --dpi (markers at true physical scale).
#   5. Single multi-page PDF (all targets) -> <xml_dir>/aruco_markers/
#      footstep_aruco_sheets.pdf: one target sheet per A4 page at true
#      physical scale (large sheets may clip at the page edge).
#
# Marker ids: target i owns ids [4i, 4i+1, 4i+2, 4i+3]
#   (front-left, front-right, back-right, back-left in the target frame;
#    x = footstep yaw direction, origin = footstep center on the top surface).
#
# Usage:
#   python3 cmd/gen_aruco_footstep_scene.py
#   python3 cmd/gen_aruco_footstep_scene.py --marker-size 0.03 --marker-spread 0.05
#   python3 cmd/gen_aruco_footstep_scene.py --shape box --size 0.1 0.08
#   python3 cmd/gen_aruco_footstep_scene.py --shape box --size 0.1 0.08 0.02

import argparse
import io
import math
import os
import shutil
import sys

import numpy as np
import cv2
from PIL import Image
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, mm
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas as pdf_canvas

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import aruco_common as ac
from gen_footstep_scene import (
    read_targets, yaw_to_quat, build_footsteps, strip_start_platform, inject,
    prepare_rows, stone_landing_poses,
    BEGIN_MARK, END_MARK, DEFAULT_CSV, DEFAULT_XML,
    DEFAULT_PLATFORM_SIZE, DEFAULT_PLATFORM_TOP, DEFAULT_BOARD,
)

ASSET_BEGIN = "<!-- BEGIN aruco marker assets (auto-generated by gen_aruco_footstep_scene.py) -->"
ASSET_END = "<!-- END aruco marker assets -->"

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJ_DIR = os.path.dirname(_THIS_DIR)

MARKER_HALF_THICK = 0.0005   # [m] visual-only thin box half thickness
MARKER_LIFT = 0.0006         # [m] center height above the footstep top face


def inject_region(xml_text, block, begin, end, closing_tag):
    """Replace the begin..end region, or insert before closing_tag."""
    b = xml_text.find(begin)
    e = xml_text.find(end)
    if b != -1 and e != -1:
        line_start = xml_text.rfind("\n", 0, b) + 1
        return xml_text[:line_start] + block + xml_text[e + len(end):]
    close = xml_text.rfind(closing_tag)
    if close == -1:
        raise ValueError(f"no {closing_tag} found in scene XML")
    line_start = xml_text.rfind("\n", 0, close) + 1
    return xml_text[:line_start] + block + "\n" + xml_text[line_start:]


def write_marker_textures(dictionary, n_targets, tex_dir, quiet_modules, bits):
    # wipe previous textures/sheets so a shorter target list leaves no orphans
    if os.path.isdir(tex_dir):
        shutil.rmtree(tex_dir)
    os.makedirs(tex_dir, exist_ok=True)
    scale = None
    for mid in range(ac.MARKERS_PER_TARGET * n_targets):
        img, scale = ac.marker_image(dictionary, mid, modules_px=32,
                                     quiet_modules=quiet_modules, bits=bits)
        # MuJoCo +Z maps PNG row 0 -> +y; rotate CW so sim matches the print
        # sheet (raw OpenCV bitmap, arrow up = +x_target).
        img = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)
        cv2.imwrite(os.path.join(tex_dir, f"marker_{mid:03d}.png"), img)
    return scale


def build_marker_assets(n_markers, tex_rel_dir):
    lines = [f"    {ASSET_BEGIN}"]
    for mid in range(n_markers):
        lines.append(
            f'    <texture name="aruco_m{mid:03d}" type="2d" '
            f'file="{tex_rel_dir}/marker_{mid:03d}.png"/>')
        lines.append(
            f'    <material name="aruco_m{mid:03d}" texture="aruco_m{mid:03d}" '
            f'specular="0" shininess="0" reflectance="0" emission="0.35"/>')
    lines.append(f"    {ASSET_END}")
    return "\n".join(lines)


def build_marker_geoms(stones, marker_size, marker_spread, tex_scale):
    """Visual-only textured thin boxes on each stepping-stone top face.

    `stones` from stone_landing_poses() (yaw-frame XY offset already applied).
    """
    half = marker_size * tex_scale / 2.0  # geom includes the white quiet zone
    centers = ac.marker_centers(marker_spread)
    lines = []
    for i, s in enumerate(stones):
        x0, y0, z_top = s["sx"], s["sy"], s["sz"]
        yaw = s["yaw"]
        c, s_yaw = math.cos(yaw), math.sin(yaw)
        qw, qx, qy, qz = yaw_to_quat(yaw)
        for j, (mx, my) in enumerate(centers):
            mid = ac.MARKERS_PER_TARGET * i + j
            gx = x0 + c * mx - s_yaw * my
            gy = y0 + s_yaw * mx + c * my
            gz = z_top + MARKER_LIFT
            lines.append(
                f'    <geom name="aruco_m{mid:03d}" type="box" '
                f'size="{half:.4f} {half:.4f} {MARKER_HALF_THICK:.4f}" '
                f'pos="{gx:.4f} {gy:.4f} {gz:.4f}" '
                f'quat="{qw:.6f} {qx:.6f} {qy:.6f} {qz:.6f}" '
                f'material="aruco_m{mid:03d}" '
                f'contype="0" conaffinity="0" group="1"/>')
    return "\n".join(lines)


METER = inch / 0.0254   # reportlab points per meter (72 pt/in)


def sheet_geometry(marker_size, marker_spread, quiet_modules, bits):
    """Physical layout of one printable 2x2 marker sheet [m]."""
    scale = (bits + 2 + 2 * quiet_modules) / float(bits + 2)
    tile = marker_size * scale                    # marker incl. quiet zone
    side = 2 * marker_spread + tile + 0.02        # +1 cm margin each side
    return scale, tile, side


def render_target_sheet(dictionary, target_index, row, marker_size, marker_spread,
                        quiet_modules, bits, dpi):
    """Render one printable sheet: 4 markers in a 2x2 layout at true scale."""
    _, tile, side = sheet_geometry(marker_size, marker_spread, quiet_modules, bits)
    px_per_m = dpi / 0.0254
    W = int(round(side * px_per_m))
    canvas = np.full((W, W), 255, np.uint8)

    def to_px(x, y):  # target frame (x fwd = sheet up, y left = sheet left)
        u = int(round(W / 2.0 - y * px_per_m))
        v = int(round(W / 2.0 - x * px_per_m))
        return u, v

    for j, (mx, my) in enumerate(ac.marker_centers(marker_spread)):
        mid = ac.MARKERS_PER_TARGET * target_index + j
        img, _ = ac.marker_image(dictionary, mid, modules_px=32,
                                 quiet_modules=quiet_modules, bits=bits,
                                 flip_v=False)
        t = int(round(tile * px_per_m))
        img = cv2.resize(img, (t, t), interpolation=cv2.INTER_NEAREST)
        u, v = to_px(mx, my)
        canvas[v - t // 2:v - t // 2 + t, u - t // 2:u - t // 2 + t] = img
    # center cross + forward arrow (sheet "up" = target +x = walking dir)
    u0, v0 = to_px(0, 0)
    cv2.drawMarker(canvas, (u0, v0), 0, cv2.MARKER_CROSS, 20, 1)
    cv2.arrowedLine(canvas, (u0, v0 - 30), (u0, v0 - 70), 0, 2, tipLength=0.3)
    cv2.putText(canvas, f"target {target_index:02d} ({row['foot']})  x->up",
                (10, W - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, 0, 1)
    # cut boundary along the sheet outer edge (~0.3 mm when printed)
    border_px = max(2, int(round(0.3 * px_per_m / 1000.0)))
    cv2.rectangle(canvas, (0, 0), (W - 1, W - 1), 0, border_px)
    return canvas


def write_print_sheets(dictionary, rows, out_dir, marker_size, marker_spread,
                       quiet_modules, bits, dpi):
    """Per-target printable PNG sheets: 4 markers at true physical scale."""
    for i, r in enumerate(rows):
        sheet = render_target_sheet(dictionary, i, r, marker_size, marker_spread,
                                    quiet_modules, bits, dpi)
        cv2.imwrite(os.path.join(out_dir, f"sheet_target_{i:02d}.png"), sheet)


def _draw_cut_guides(c, x0, y0, side_pts, mark_len=10, gap=3):
    """Cut boundary on the sheet edge + corner ticks extending outside."""
    x1, y1 = x0 + side_pts, y0 + side_pts
    c.setStrokeColorRGB(0, 0, 0)
    c.setLineWidth(0.6)
    c.rect(x0, y0, side_pts, side_pts, stroke=1, fill=0)

    c.setStrokeColorRGB(0.45, 0.45, 0.45)
    c.setLineWidth(0.4)
    g, m = gap, mark_len
    # bottom-left
    c.line(x0 - g - m, y0, x0 - g, y0)
    c.line(x0, y0 - g - m, x0, y0 - g)
    # bottom-right
    c.line(x1 + g, y0, x1 + g + m, y0)
    c.line(x1, y0 - g - m, x1, y0 - g)
    # top-left
    c.line(x0 - g - m, y1, x0 - g, y1)
    c.line(x0, y1 + g, x0, y1 + g + m)
    # top-right
    c.line(x1 + g, y1, x1 + g + m, y1)
    c.line(x1, y1 + g, x1, y1 + g + m)


def _draw_sheet_on_page(c, dictionary, target_index, row, x0, y0, sheet_pts,
                        marker_size, marker_spread, quiet_modules, bits, dpi):
    sheet = render_target_sheet(dictionary, target_index, row, marker_size,
                                marker_spread, quiet_modules, bits, dpi)
    buf = io.BytesIO()
    Image.fromarray(sheet, mode="L").save(buf, format="PNG")
    buf.seek(0)
    c.drawImage(ImageReader(buf), x0, y0, width=sheet_pts, height=sheet_pts)
    _draw_cut_guides(c, x0, y0, sheet_pts)


def write_print_pdf(dictionary, rows, pdf_path, marker_size, marker_spread,
                    quiet_modules, bits, dpi):
    """One target sheet per A4 page at true physical scale (may clip)."""
    _, _, side = sheet_geometry(marker_size, marker_spread, quiet_modules, bits)
    sheet_pts = side * METER
    page_w, page_h = A4
    x0 = (page_w - sheet_pts) / 2.0
    y0 = (page_h - sheet_pts) / 2.0

    if sheet_pts > min(page_w, page_h):
        print(f"warning: sheet {side * 1000:.0f} mm exceeds A4; "
              f"edges will clip when printed at 100% / Actual size")

    print(f"[gen_aruco] print PDF: A4, 1 target/page, "
          f"sheet {side * 1000:.0f} mm (100% / Actual size)")

    c = pdf_canvas.Canvas(pdf_path, pagesize=A4)
    for i, r in enumerate(rows):
        _draw_sheet_on_page(c, dictionary, i, r, x0, y0, sheet_pts,
                            marker_size, marker_spread,
                            quiet_modules, bits, dpi)
        c.setFillColorRGB(0, 0, 0)
        c.setFont("Helvetica", 7)
        c.drawCentredString(
            page_w / 2.0, 6 * mm,
            f"A4: 100% / Actual size  |  sheet {side * 1000:.0f} mm  |  "
            "cut along solid border (may clip if sheet > A4)")
        c.showPage()
    c.save()


if __name__ == "__main__":
    p = argparse.ArgumentParser(
        description="Generate footstep geoms + 4 ArUco markers per target in a MuJoCo scene XML.")
    p.add_argument("--csv", default=DEFAULT_CSV)
    p.add_argument("--xml", default=DEFAULT_XML)
    p.add_argument("--board", default=DEFAULT_BOARD,
                   help="output board metadata JSON (read by the perception node)")
    p.add_argument("--shape", choices=["box", "cylinder"], default="cylinder")
    p.add_argument("--size", nargs="+", type=float, default=[0.125, 0.06],
                   metavar="H",
                   help="HX HY [HZ]: box half-extents [m] (cylinder: radius=HX). "
                        "If HZ given, vertical half-size is fixed (top at pos_z); "
                        "otherwise height is from ground to pos_z")
    p.add_argument("--plane-margin", type=float, default=3.0)
    p.add_argument("--platform-size", nargs=2, type=float,
                   default=list(DEFAULT_PLATFORM_SIZE), metavar=("HX", "HY"))
    p.add_argument("--platform-top", type=float, default=DEFAULT_PLATFORM_TOP)
    p.add_argument("--offset-x", type=float, default=-0.0,
                   help="stone/ArUco XY offset in each foot's yaw frame, forward [m] "
                        "(red/blue spheres stay on CSV)")
    p.add_argument("--offset-y", type=float, default=0.0,
                   help="stone/ArUco XY offset in each foot's yaw frame, left [m]")
    p.add_argument("--offset-z", type=float, default=0.0,
                   help="stone/ArUco top height offset in world-up [m]")
    p.add_argument("--center", action="store_true")
    # marker parameters
    # p.add_argument("--marker-size", type=float, default=ac.DEFAULT_MARKER_SIZE,
    p.add_argument("--marker-size", type=float, default=0.06,
                   help="black-border side length [m] (default 0.06 = 6 cm; "
                        "PDF is always 1 sheet per A4, large sheets may clip)")
    p.add_argument("--marker-spread", type=float, default=0.05,
                   help="|x|=|y| offset of the 4 marker centers [m]")
    p.add_argument("--dict-bits", type=int, default=ac.DEFAULT_DICT_BITS,
                   help="marker bit-grid size (default 4 -> standard DICT_4X4; "
                        "3 -> custom 3x3-bit dict, only reliable with few ids)")
    p.add_argument("--dict-seed", type=int, default=ac.DEFAULT_DICT_SEED)
    p.add_argument("--quiet-modules", type=int, default=ac.DEFAULT_QUIET_MODULES)
    p.add_argument("--dpi", type=int, default=300, help="print sheet resolution")
    p.add_argument("--pdf", default=None,
                   help="output PDF path (default: <xml_dir>/aruco_markers/"
                        "footstep_aruco_sheets.pdf)")
    p.add_argument("--no-sheets", action="store_true",
                   help="skip printable per-target PNG sheets and PDF")
    args = p.parse_args()
    if len(args.size) not in (2, 3):
        p.error("--size expects HX HY [HZ] (2 or 3 values)")

    rows = read_targets(args.csv)
    n_targets = len(rows)
    n_markers = ac.MARKERS_PER_TARGET * n_targets
    dict_size = max(ac.DEFAULT_DICT_SIZE, n_markers)
    dictionary = ac.make_dictionary(args.dict_bits, dict_size, args.dict_seed)

    off = (args.offset_x, args.offset_y, args.offset_z)
    # Same recenter + yaw-frame stone poses as build_footsteps (spheres=CSV).
    work = prepare_rows(rows, center_y=args.center)
    stones = stone_landing_poses(work, off)

    # 1) footstep pillar/platform/ground + CSV spheres
    geom_block, z_ground, z_min = build_footsteps(
        rows, args.shape, args.size, off, center_y=args.center,
        plane_margin=args.plane_margin,
        platform_size=tuple(args.platform_size),
        platform_top=args.platform_top)

    # 2) ArUco textures + geoms on stone tops (offset landings)
    xml_dir = os.path.dirname(os.path.abspath(args.xml))
    tex_dir = os.path.join(xml_dir, "aruco_markers")
    tex_scale = write_marker_textures(dictionary, n_targets, tex_dir,
                                      args.quiet_modules, args.dict_bits)
    marker_geoms = build_marker_geoms(stones, args.marker_size,
                                      args.marker_spread, tex_scale)
    geom_block = geom_block.replace(f"\n    {END_MARK}",
                                    f"\n{marker_geoms}\n    {END_MARK}")
    asset_block = build_marker_assets(n_markers, "aruco_markers")

    # 3) board metadata = stone top-surface center (where ArUco actually sit)
    targets_meta = [
        {"index": i, "foot": s["foot"],
         "world": {"x": s["sx"], "y": s["sy"], "z": s["sz"], "yaw": s["yaw"]}}
        for i, s in enumerate(stones)
    ]
    ac.save_board(args.board, targets_meta, args.dict_bits, dict_size,
                  args.dict_seed, args.marker_size, args.marker_spread,
                  args.quiet_modules)

    # 4) inject into scene XML (inject strips rocky/footstep/aruco regions first)
    with open(args.xml) as f:
        xml_text = f.read()
    xml_text = strip_start_platform(xml_text)
    xml_text = inject(xml_text, geom_block)                      # worldbody
    xml_text = inject_region(xml_text, asset_block, ASSET_BEGIN,  # assets
                             ASSET_END, "</asset>")
    with open(args.xml, "w") as f:
        f.write(xml_text)

    # 5) printable sheets + PDF
    pdf_path = None
    if not args.no_sheets:
        write_print_sheets(dictionary, rows, tex_dir, args.marker_size,
                           args.marker_spread, args.quiet_modules,
                           args.dict_bits, args.dpi)
        pdf_path = args.pdf or os.path.join(tex_dir, "footstep_aruco_sheets.pdf")
        write_print_pdf(dictionary, rows, pdf_path, args.marker_size,
                        args.marker_spread, args.quiet_modules,
                        args.dict_bits, args.dpi)

    print(f"Wrote {n_targets} {args.shape} footstep targets + {n_markers} "
          f"ArUco markers into {args.xml}")
    print(f"  textures/sheets : {tex_dir}")
    if pdf_path:
        print(f"  print PDF       : {pdf_path}")
    print(f"  board metadata  : {args.board}")
